spring.datasource.url=jdbc:mysql://localhost:3306/readit_db
spring.datasource.username=root
spring.datasource.password=Redtaylor12.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.jwt.secret=ZbsALkkl/4AeUaC99EmrIOAow30WG6srvg9L8QVOnnU=
app.jwt.expiration=86400000